### ISSUE TITLE
Re-introduce multi-offer push ('upsert')

### ISSUE THREAD

**Issue by tomlankhorst** [developersbolcom/retailer-api#30]
Currently, only one offer can be [pushed](https://api.bol.com/retailer/public/redoc/v3#tag/Offers) at a time, identified by an offer ID. 
Please, re-introduce the multi-offer push [(up to 50 offers) as implemented in the Plaza v2 API](https://developers.bol.com/create-and-update/).

**Comment by jwalgemoed** [comment]
Hi @tomlankhorst, thank you for your message. I'm curious, why would you need this functionality specifically? There's nothing really blocking you from doing a series of subsequent requests instead of one bigger request (other than maybe the rate limits being to strict). 

Also I'd like to highlight the distinction between bulk offer updates and 'upserts', these are not the same thing. We've abandoned the concept of upserts allowing retailers to update offers based on a unique key, giving a more explicit nature to the update requests.

**Comment by tomlankhorst** [comment]
Thank you for your prompt reply. In a modern e-commerce landscape, prices are adjusted very frequently based on supply, demand, promotions, the competitor landscape, etc. Combined with a large offer catalogue, this might requires the batch update of hundreds of products at once. 

Though it is still possible to implement this through single requests, it will require 50 times more requests on the client side, introducing quite some overhead.

**Comment by jwalgemoed** [comment]
Hi @tomlankhorst, you are not wrong, there's an added overhead regarding sending multiple singles versus a larger bulk request. However, this is also the case with bigger bulk requests on our backend infrastructure. This overhead is sometimes greatly exaggerated; doing single updates in parallel can at times be marginally slower than bulking one big request. Given reasonable connection speeds this should be very manageable. 

In addition, the semantics of a bulk request need to be well defined, something which isn't always immediately clear when sending bulk updates. Meaning: how can you properly communicate failure/success scenarios? When is a bulk update considered successful, when all updates succeed or de we just check for individual update successes? We want to provide explicit feedback regarding offer updates/creations/deletions to be consistent with the rest of the API, whereas the v2 version was more of the fire-and-forget variety. This was easier to do in singles. 

When dealing with consistency this is also something we wanted to keep in mind, we do not offer bulk updates anywhere else in the API at this time, so adding them for this particular case would be a departure from our conventions.

Finally, it is worth noting that we are aware that some updates are occurring more often than others. We see users create offers, and update the specifics far less than they are updating stock and/or price information. This is why we separated out these endpoints, so we can more efficiently handle these updates as stock and price updates are relatively cheap, where creation and structural updates of offers are not trivial. This is not the main reason for creating separate endpoints for these actions, there are also partners that integrate with the API that have requested these separate endpoints so they do not need to provide all offer details when they simply want to update stock. 

I hope this clarifies the situation for you. Feel free to reach out if you have any questions regarding this.
