### ISSUE TITLE
Document all rate-limiting 'groups'

### ISSUE THREAD

**Issue by tomlankhorst** [developersbolcom/retailer-api#31]
An overview of endpoints and corresponding rate-limits would be very useful. 

Currently, there is an [incomplete list](https://api.bol.com/retailer/public/conventions/index.html) which mentions rate-limits that are not even current. E.g., `/retailer/orders` would have a limit of 7, according to the documentation while `X-RateLimit-Limit` header states 20. 

Please document all endpoints and corresponding rate-limits such that clients can take this into consideration when designing their applications and rate-limiting mechanisms.

**Comment by idebruijn** [comment]
The incomplete list is a subset of our current rate limits with example values.

We have a story on our backlog to dynamically publish all endpoints and corresponding rate-limits because they can change over time.  When this comes available we document this in our release-notes.
