### ISSUE TITLE
Get inbounds shipment list response suggests containing products element

### ISSUE THREAD

**Issue by avido** [developersbolcom/retailer-api#36]
Get inbounds shipment list response suggests containing products element in redoc documentation, however this element isn't present.

**Comment by joostvandermeer** [comment]
Hi,

Thanks for your question!

You may have noticed that, at the moment, our GitHub page is not yet very active. We've used it to support a closed beta of the v3 API that is now live. We plan to start using it to start communicating our roadmap and get retailer input, but for now, we do not yet have the team in place to monitor the page and actively answer questions. Therefore, we have temporarily closed the link to it on our documentation pages.

I am hoping to get things going on GitHub again (no longer as part of a closed beta, but public) in the second half of may. Until then, the quickest way to get an answer to your question is by contacting the partnerservice department: https://developers.bol.com/contactformulier/.

I am sorry for the inconvenience.

Kind regards,

Joost
