### ISSUE TITLE
Multiple offers per product

### ISSUE THREAD

**Issue by tomlankhorst** [developersbolcom/retailer-api#46]
Currently, a retailer can present a single offer to Bol.com for both NL and BE. 

Now, as these countries are very much alike, in terms of language, location, VAT rates, membership of the EU, it is not a big deal yet that you cannot differentiate between these orders. 

I can, however, imagine that this might change in the future. For example, Bol.com might add a German store: different language, harder to ensure delivery times, different VAT rates, etc. 

How will this future look like: do we need a separate 'Retailer' account to differentiate between countries for example, or will there be a situation in which a retailer can submit multiple offers for a single product, based on location or language or vat rate. 

This is useful to know when designing an appropriate data structure for managing this information.

**Comment by joostvandermeer** [comment]
Hi Tom,

Thanks for your question!

You may have noticed that, at the moment, our GitHub page is not yet very active. We've used it to support a closed beta of the v3 API that is now live. We plan to start using it to start communicating our roadmap and get retailer input, but for now, we do not yet have the team in place to monitor the page and actively answer questions. Therefore, we have temporarily closed the link to it on our documentation pages.

I am hoping to get things going on GitHub again (no longer as part of a closed beta, but public) in the second half of may. Until then, the quickest way to get an answer to your question is by contacting the partnerservice department: https://developers.bol.com/contactformulier/.

I am sorry for the inconvenience.

Kind regards,

Joost
