### ISSUE TITLE
Fetching multiple orders / shipments with meta data

### ISSUE THREAD

**Issue by FiveX-dev** [developersbolcom/retailer-api#51]
Ability when fetching multiple orders  (GET - /retailer-demo/orders) or shipments (GET - /retailer-demo/shipments) to add product specific attributes to the response.

We would like to see the following attributes available in the array:

"orderItemId": "6042823871",
"ean": "8717418510749",
"title": "Star Wars - The happy family 2",
"quantity": 3,
"offerPrice": 33,
"transactionFee": 2.22,

**Comment by FiveX-dev** [comment]
We also need the country of the order delivery: NL / BE would be great.

**Comment by derkvw** [comment]
Hi,

Thank you for your question about the bol.com Retailer API.
‘developersbolcom.github.io’ is used for communication about beta components only.
You can also find this information in the README.

Your question / remark does not seem to be about a beta component.
Please feel free to contact us about other topics via the usual route:

For all other questions / remarks you can contact Partnerservice:
https://developers.bol.com/contactformulier/ 

Kind Regards,

Team Retailer API
