### ISSUE TITLE
status 500 returns from get Offers

### ISSUE THREAD

**Issue by RobbinRook** [developersbolcom/retailer-api#53]
GuzzleHttp\Exception\ServerException Server error: `GET https://api.bol.com/retailer/offers/xxxxxxxxxx` resulted in a `500 Internal Server Error` response:
{"type":"https://api.bol.com/problems","title":"Internal Server Error","status":500,"detail":"Unknown error while retrieving offer with id: xxxxxxxxxx.","host":"Instance-004","instance":"https://api.bol.com/retailer/offers/xxxxxxxxxx"}

This keeps on happening for the last few days. For the privacy part i have removed the offer ID

**Comment by derkvw** [comment]
Hi,

Thank you for your question about the bol.com Retailer API.
‘developersbolcom.github.io’ is used for communication about beta components only.
You can also find this information in the README.

Your question / remark does not seem to be about a beta component.
Please feel free to contact us about other topics via the usual route:

For all other questions / remarks you can contact Partnerservice:
https://developers.bol.com/contactformulier/ 

Kind Regards,

Team Retailer API
