### ISSUE TITLE
404 error: Forecast for offer-id not found

### ISSUE THREAD

**Issue by Senergia** [developersbolcom/retailer-api#54]
Hi API v4 team,

Your PO has recently given my account (1163640) access the API v4. I'm trying to run the insights/sales-forecast API but I'm getting a 404 not found response. The offer-id I'm using is from an existing offer obtained through the API v3 > offers/export. 

This is the URL i'm using: https://api.bol.com/retailer-demo/insights/sales-forecast?offer-id=844c9436-d698-4155-aa6f-2ddfb9a86750&weeks-ahead=3

I have set headers Accept / application/vnd.retailer.v4+json and I'm using the Bearer token.

**Comment by koenmolkenboer** [comment]
Can you try it without the '-demo' in the URL, like: https://api.bol.com/retailer/insights/sales-forecast?offer-id=844c9436-d698-4155-aa6f-2ddfb9a86750&weeks-ahead=3

**Comment by Senergia** [comment]
Thank you for your reply. I tried without ' -demo' in the URL with the same URL as you mentioned. Now I'm getting a 403 Unauthorized Request error.

**Comment by koenmolkenboer** [comment]
I checked your authorization and everything looks good. Did you generate a new access token, because the token has a limited time? Are you able to access other endpoints?

**Comment by Senergia** [comment]
I did generate a new access token. If I'm waiting to long I'm getting a 401 error after which I regenerate the token and get a 403 error.

I checked another BETA endpoint and it works perfectly with the same offer id: retailer/insights/offer?offer-id=844c9436-d698-4155-aa6f-2ddfb9a86750&period=MONTH&number-of-periods=1&name=PRODUCT_VISITS&name=BUY_BOX_PERCENTAGE

So it really seems to be related to this specific sales-forecast service... I hope this helps

**Comment by koenmolkenboer** [comment]
We changed some things on the rate limiter, so could you try it again?

**Comment by Senergia** [comment]
Yes that works. Thank you very much!

**Comment by koenmolkenboer** [comment]
Okay, enjoy the API!

**Comment by DanielvdAkker** [comment]
Hi. Same problem here... I can retrieve the offer insights, but not the sales-forecast. Is the rate-limit still "25 requests per 1 seconds"?

**Comment by DanielvdAkker** [comment]
I have used another offer-id, and I receive some information now. The 404 for a valid offer-id is quite confusing, not sure why it occurs.

**Comment by koenmolkenboer** [comment]
This is possible due to the fact that we do not have a forecast for each product/offer. If there is no forecast available for an offer you will get a 404 response. 
I checked your offer with id 9f671099-a043-4b02-e053-4782010a7b13 and for that offer there is no forecast.
