### ISSUE TITLE
Replacement of Product Contents' `Validation Report` model

### ISSUE THREAD

**Issue by stetteroox** [developersbolcom/retailer-api#55]
At this moment you are able to execute `GET /v4/retailer/content/validation-report/{uploadId}` which gives back a `Validation Report` that provides an overview of all rejected attributes of the supplied upload id.

But we foresee that the current response model is not generic enough to support different types of `Report` models we want to support in the future. We want to change the existing model to a generic model that is more flexible, reusable and extensible for future changes.

**Current model**

```json
{
  "status": "VALIDATED_WITH_FAILURES",
  "rejectedProductContents": [
    {
      "internalReference": "ref0122",
      "rejectedAttributes": [
        {
          "attributeId": "Weight",
          "rejectionErrors": [
            {
              "code": 1001,
              "message": "Attribute did not validate.",
              "reason": "Does not meet field requirements. Make sure your input aligns with our data model."
            }
          ]
        }
      ]
    }
  ]
}
```

**Proposed model**

```json
{
  "status": "VALIDATED_WITH_FAILURES", 
  "productContents": [
    {
      "internalReference": "ref0122",
      "status": "VALIDATED_WITH_FAILURES",
      "rejectedAttributes": [
        {
          "id": "Weight",
          "errors": [
            {
              "code": 2014,
              "codeDescription": "Invalid unit",
              "reason": "Is not a valid number"
            }
          ]
        },
        {
          "id": "Release date",
          "errors": [
            {
              "code": 2008,
              "codeDescription": "Invalid isodatetime",
              "reason": "Is not a valid iso date time"
            }
          ]
        }
      ]
    },
    {
      "internalReference": "ref0123",
      "status": "VALIDATED_OK"
    }
  ]
}
```

With the new model we are able to extend the `Report` types using the same model, e.g. we could generate a `Publication Report` that provides the same product overview with rejected attributes that are not published, without changing the models' inner structure.

What I would like to ask:
* Do you prefer the generic model over the old model?
* Do you have other suggestions for the new generic model?
* In the new model we also return products that successfully passed validation. Do you think this is a good idea?

**Comment by ceijssen** [comment]
> In the new model we also return products that successfully passed validation. Do you think this is a good idea?

It's nice because it allows us to compare the amount of "operations" vs "results". If we send for example 10 items, but receive error results for only 9 items, what happened to the 10th item? Was it successful or not? In the new model, we know for sure this item was received successfully.

**Comment by marcselman** [comment]
Looks fine to me but I'm wondering, you have the `rejectedAttributes` array but couldn't there be other reasons a product is not valid other than attributes?

**Comment by s-tetteroo** [comment]
@marcselman in fact we always report back on attribute level. There could be reasons where we reject the complete product (e.g. when we are not able to link the product internally). In that case we still provide error details on attribute level.

**Comment by marcselman** [comment]
@s-tetteroo Theoretically, if all attributes are fine but the product is still rejected for some other reason, what would the JSON model look like then?

**Comment by s-tetteroo** [comment]
@marcselman the JSON model remains the same, the only difference is that all attributes will be rejected with code 1000 for example.

**Comment by marcselman** [comment]
@s-tetteroo Isn't that a lot of overhead. Products can have a lot of attributes so this could generate very big JSON elements. Or is this theoretical case very rare?

**Comment by s-tetteroo** [comment]
@marcselman That is true. We don't have an exact number of products that will be completely rejected based on their supplied attributes. As long as the Data Model is integrated nicely I would guess it won't happen that often, but we can never be sure.

Also we could extend the proposed model easily with an extra status on product level, if we expect that rejection on product level is going to happen more often in the future.

I will discuss this case, and take in consideration whether we want to include a `solution` right away or that we leave it out of scope for now.
