### ISSUE TITLE
Omit 'name' property in OfferInsightsRequestModel => both buy block as well as product visits

### ISSUE THREAD

**Issue by nopfinance** [developersbolcom/retailer-api#57]
When a product is visited 100 times during a given period, and the buy block percentage for said period is 6% than that more or less means that the number of impressions of our offer is actually '6'. (assuming the Buy block percentage is measured during a product visit)

Currently I have to execute 2 requests tot the insight api: one for buy block and one for product visits. Only then will be able to calculate the absolute amount of impressions.

I think it would save performance if the end point gives both values in one API call, for example by omitting the Name property of the OfferInsightsRequest

**Comment by nopfinance** [comment]
Thx Jurian!

**Comment by nopfinance** [comment]
Technically: PRODUCT_VISITS should be OFFER_VISITS as it will reflect only the number of times my offer was shown in de buy block... PRODUCT_VISITS has a broader scope.

**Comment by jdekorne** [comment]
Thanks for the feedback, I agree with you that OFFER_VISITS is a better name. We will consider changing this in the official version.
