### ISSUE TITLE
Offer API csv request endpoint (POST) always PENDING

### ISSUE THREAD

**Issue by FiveX-dev** [developersbolcom/retailer-api#59]
The following request always results in status PENDING:

Endpoint: https://api.bol.com/retailer/offers/export
Method: POST
Body: {"format": "CSV”}

I saw that you guys did some maintenance the 10th of April, maybe it has something to do with that? [LINK TO MAINTENANCE](https://developers.bol.com/nieuws/plaza-api/nieuws/10-04-2020-api-and-offer-ftps-scheduled-maintenance-offer-service/)

**Comment by Senergia** [comment]
I have the same issue with my account. The last successful request was on 13th of April. It started failing from April 14 and onward. Our inventory management really depends on this endpoint so I would really appreciate it if you could have a look.

**Comment by derkvw** [comment]
hi, we are currently looking into that issue. Please use the contact channels mentioned on this page for operational issues: https://developers.bol.com/contactformulier/ 

This GitHub page is only for feedback on beta endpoints.
