### ISSUE TITLE
Endpoint for retrieving the picklist(pakbon) of the orderById in FBR

### ISSUE THREAD

**Issue by Rich040371** [developersbolcom/retailer-api#61]
Hello Team,

I'm missing the endpoint where to get the picklist / packlist (pakbon) by order id in case of FBR.
Ik mis in de Api V3 de endpoint om een pakbon te verkrijgen per order id in geval van FBR.

Greetings
Richard

**Comment by avido** [comment]
Die is er niet

**Comment by Rich040371** [comment]
Nee dat zie ik, maar zal wel handig zijn!
Is er een rede voor dat deze ontbreekt?

**Comment by avido** [comment]
omdat het FBR betreft. Bol heeft geen inzicht in hoe jullie interne processen lopen en kan derhalve ook niet bepalen hoe een pakbon er dan uit moet komen te zien.

**Comment by nopfinance** [comment]
Wat je moet doen is door de pagina's van shipments lopen. In NopFinance hebben we het zo geregeld dat de order leading is en als de order gemist wordt bij FBR (bijvoorbeeld omdat de API koppeling offline is en de gebruiker via het bol dashboard moet werken) de order afgeleid wordt van de shipments. Dus per shipment bekijken we of de order al bestaat. Zo niet dan wordt de order alsnog aangemaakt. 

Dit mechanisme **moet** je echt implementeren anders ga je de fout in bij FBB! Bij FBB vang je de meeste orders namelijk niet omdat die razendsnel wordt afgehandeld bij bol.

Mis je zowel de shipment als de order? Dan is er nog een tweede reparatie-ronde en die ontstaat op het moment dat je de maandelijkse invoice inleest via de API.

Als ik dan kijk naar NopFinance dan is het proces grofweg als volgt opgezet:

1) Lees FBB en FBR orders
2) Lees Shipments en reconstrueer FBB en FBR orders indien nodig
3) Lees maandelijks de inkoopfactuur en reconstreer FBB en FBR orders indien nodig

Deze aanpak is nodig omdat je daarmee een zo'n acuraat mogelijke voorraad kunt bijhouden en omdat je ERP dan weet wanneer er een vordering op bol ontstaat.

**Comment by Rich040371** [comment]
> Wat je moet doen is door de pagina's van shipments lopen. In NopFinance hebben we het zo geregeld dat de order leading is en als de order gemist wordt bij FBR (bijvoorbeeld omdat de API koppeling offline is en de gebruiker via het bol dashboard moet werken) de order afgeleid wordt van de shipments. Dus per shipment bekijken we of de order al bestaat. Zo niet dan wordt de order alsnog aangemaakt.
> 
> Dit mechanisme **moet** je echt implementeren anders ga je de fout in bij FBB! Bij FBB vang je de meeste orders namelijk niet omdat die razendsnel wordt afgehandeld bij bol.
> 
> Mis je zowel de shipment als de order? Dan is er nog een tweede reparatie-ronde en die ontstaat op het moment dat je de maandelijkse invoice inleest via de API.
> 
> Als ik dan kijk naar NopFinance dan is het proces grofweg als volgt opgezet:
> 
> 1. Lees FBB en FBR orders
> 2. Lees Shipments en reconstrueer FBB en FBR orders indien nodig
> 3. Lees maandelijks de inkoopfactuur en reconstreer FBB en FBR orders indien nodig
> 
> Deze aanpak is nodig omdat je daarmee een zo'n acuraat mogelijke voorraad kunt bijhouden en omdat je ERP dan weet wanneer er een vordering op bol ontstaat.

Dank je wel voor je antwoord echter denk ik dat deze niet bij deze Post bedoelt is!? over het verkrijgen van de Pakbon.

**Comment by nopfinance** [comment]
Dit is wel degelijk een antwoord op je vraag. Ik beschrijf namelijk hoe je afhandeling van shipments tbv een order dient uit te voeren zodat je de gevraagde informatie verkrijgt. 

Om het simpel te houden: itereer over alle shipments van de afgelopen 12 weken en zoek daarin naar de shipment met gevraagde order id.

**Comment by Rich040371** [comment]
Hoi, dankjewel wederom voor je antwoord. Maar zie niet zo goed hoe mij dat een pdf van de pakbon geeft. Heb dat inmiddels al weten af te vangen. Of mailen we langs elkaar heen en is er weldegelijk een endpoint waarmee pakbon als pdf kunnen worden opgeslagen.


Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: nopfinance <notifications@github.com>
Verzonden: Tuesday, July 14, 2020 8:58:48 PM
Aan: developersbolcom/developersbolcom.github.io <developersbolcom.github.io@noreply.github.com>
CC: Richard <rich040371@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [developersbolcom/developersbolcom.github.io] Endpoint for retrieving the picklist(pakbon) of the orderById in FBR (#61)


Dit is wel degelijk een antwoord op je vraag. Ik beschrijf namelijk hoe je afhandeling van shipments tbv een order dient uit te voeren zodat je de gevraagde informatie verkrijgt.

Om het simpel te houden: itereer over alle shipments van de afgelopen 12 weken en zoek daarin naar de shipment met gevraagde order id.

**Comment by nopfinance** [comment]
Nee er is geen pdf endpoint voor shipments. Zou ook vreemd zijn aangezien je de shipment pas aanmaakt als je de order 'gepickt' hebt.

Maar het staat je vrij om met de shipment info zelf een goede, bol conforme, pakbon te printen. Wij doen dat in NopFinance ook: een pakbon met storage informatie en extra info om retouren sneller af te handelen.

**Comment by Rich040371** [comment]
NopFinance is? Een bol afdeling voor de api versies? Same here, ook pakbonnen met magazijn locatie. Wat heb je nou aan standaard pakbonnen ;-)


Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: nopfinance <notifications@github.com>
Verzonden: Tuesday, July 14, 2020 9:40:08 PM
Aan: developersbolcom/developersbolcom.github.io <developersbolcom.github.io@noreply.github.com>
CC: Richard <rich040371@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [developersbolcom/developersbolcom.github.io] Endpoint for retrieving the picklist(pakbon) of the orderById in FBR (#61)


Nee er is geen pdf endpoint voor shipments. Zou ook vreemd zijn aangezien je de shipment pas aanmaakt als je de order 'gepickt' hebt.

Maar het staat je vrij om met de shipment info zelf een goede, bol conforme, pakbon te printen. Wij doen dat in NopFinance ook: een pakbon met storage informatie en extra info om retouren sneller af te handelen.

**Comment by nopfinance** [comment]
NopFinance is een erp systeem met 90% bol.com api dekking

**Comment by RGeerlings** [comment]
Hi Richard, 

Het is wellicht handig te weten dat de pakbon niet meer verplicht is zolang het bestelnummer maar op het verzendlabel staat. Dat scheelt onnodig papier, en het scheelt jullie een handeling! Je kunt er meer over lezen op ons Partner Platform: https://partnerplatform.bol.com/nieuws/de-pakbon-is-niet-altijd-meer-verplicht

Met vriendelijke groet,
Ron Geerlings - bol.com

**Comment by nopfinance** [comment]
Houd er rekening mee dat als je bestelnummer op het label staat, en je pakket onafgelverd retour komt. Je originele label geheel overplakt is met stickers en een nieuw label. De tijd die het dan kost om uit te zoeken om welke klant het gaat kan nog wel eens de kosten van papier overstijgen. Wij plakken altijd in de verpakking een A8 label met daarop het bestelnummer. Dat kost ons 0,02ct per sticker en 4 seconden aan tijd => 0,04ct
