### ISSUE TITLE
retailer API 4 docs

### ISSUE THREAD

**Issue by nopfinance** [developersbolcom/retailer-api#62]
Retailer API 4 is expected in october 2020. Are the endpoint docs anywhere to be found?

**Comment by derkvw** [comment]
hi, the full documentation of the v4 is not ready for publication yet. We do have v4 BETA components for which you can find the details here: https://developers.bol.com/beta-program-retailer-api/  also have a look at the child pages.
 
Keep an eye on the news page to see when we pubish more info about the v4: https://developers.bol.com/nieuws/

**Comment by mroosendaal** [comment]
Retailer API V4 launched
