### ISSUE TITLE
Some concerns regarding the pickupPoint implementation

### ISSUE THREAD

**Issue by nopfinance** [developersbolcom/retailer-api#63]
About endpoint 'Get an open order by order id

Returns member: pickupPoint: true
CustomerDetails.ShipmentDetails then contains the pickupPointName

So far so good...however..

What is missing is the holiday/vacation information of the said pickup point. Since many pickup points are small local shops they will inevitably close shop every once in a while.

Now suppose a seller has 8 days of delivery promise there is a slight possibility that the package ends up at a pickup point that is on holiday by the time the package arrives, or just before the PuPcloses shop. 

If the order were to contain some information on whether the shop is about to close somewhere during the delivery promise period plus 1 week there the seller may contact the customer and agree on a different PuP.

**Comment by Mauricevh88** [comment]
Hi NopFinance,

I understand your question. It is important to know that you need to configure a workschedule (workdays of the seller) specifically for AH PUP in the seller dashboard. This is required before you can actually use AH PUP delivery and connect it to your offers. 

In this workschedule the seller can't have a delivery promise of 8 days. The option will only be shown on bol.com if the partner is working on the day before, until the cut-off which can be also configured in the work-schedule.

Next to that the Albert Heijn isn't really a small local shop, but a supermarket which is opened almost every day of the week. The only slight possibility when the supermarket is closed could be on Sunday or holidays. These particular holidays are configured in our back-end and connected to each separate workschedule for each seperate seller.

Does this answer your question?
