### ISSUE TITLE
Performance indicator Track and trace shows incorrect condition (v3)

### ISSUE THREAD

**Issue by xclusionmedia** [developersbolcom/retailer-api#66]
Not sure if v3 issues can also be posted here, but I'll try my luck :)

**What are you trying to accomplish?**
I'm fetching the performance indicators and processing the output. The endpoint provides a >= or <= based on the sellers score. The output for track & trace shows the wrong norm condition. Please see the response below for Track & Trace

The norm is set to 1.0
The seller score is 0.087
The distance is correctly set to 0.913
But the condition is set to **>=** while 0.087 is actually below (<=) the norm of 1.0. So should be <=

The other indicators show the correct condition.

**Which endpoint(s) are you using?**
{{base_url}}/{{environment}}/insights/performance/indicator?week=37&year=2020&name=TRACK_AND_TRACE

{
    "performanceIndicators": [
        {
            "name": "track_and_trace",
            "type": "percentage",
            "details": {
                "period": {
                    "week": "37",
                    "year": "2020"
                },
                "score": {
                    "conforms": false,
                    "numerator": 2,
                    "denominator": 23,
                    **"value": 0.087,**
                    **"distanceToNorm": 0.913**
                },
                "norm": {
                    **"condition": ">=",**
                    **"value": 1.0**
                }
            }
        }
    ]
}

**Comment by dmathot** [comment]
The norm condition is not related to the specific seller's performance instead it describes the norm we expect for the track and trace KPI in general. Eg. in this case the norm condition: `>=` indicates every seller is expected to have a track of trace score (`value`) of `1.0`.

Although this is not a bug we will have a look at the documentation and make sure it is explained there as well.

**Comment by xclusionmedia** [comment]
I see, I get it now. Thanks for making it clear!
