### ISSUE TITLE
Insights Sales Forecast API is not working anymore > Gateway Timeout error

### ISSUE THREAD

**Issue by Senergia** [developersbolcom/retailer-api#68]
I have an automated script that pulls the sales forecast every 4 hours. I use this script for inventory management.
However, since this morning the API is returning a 504, Gateway Timeout.
This is for Bol account 1163640

For example for this offer id: https://api.bol.com/retailer/insights/sales-forecast?offer-id=42460cb2-4841-4521-84ba-c90d47467712&weeks-ahead=4

**Comment by jwalgemoed** [comment]
@Senergia Did you receive this error for all of your request, or a few of them? Under high pressure, we return these errors, which can in turn be retried by the client. 

Please keep in mind that ideally you'd apply a bit of backoff time, not hammer the API with the retries as this would yield the exact same error message.
