### ISSUE TITLE
When creating subscription google script post URL is too long

### ISSUE THREAD

**Issue by janportheine** [developersbolcom/retailer-api#69]
When creating a subscription with a google script url it says the URL is too long:

A problem occurred handling a request: /problems/validation-failed {400, Your request parameters didn't validate., violations=[{name=url, reason=size must be between 0 and 80}]}

Is there a workaround or can this be lengthened?

---
sorry used bug label.

**Comment by mroosendaal** [comment]
@janportheine thanks for creating an issue, unfortunatly there is too little information for us  properly  help you (we advise to use the 'Bug Report' when creating an issue).

* Subscription: do you mean the Subscription API (https://api.bol.com/retailer/public/Retailer-API/beta-program/subscription-api.html)?
* Do you have an example of the script you use?
* Do you have an example of the request the script produces?

And if you can think of some more information that would help us that would be really appreciated.

With kind regards,
M. Roosendaal 
bol.com

**Comment by janportheine** [comment]
Hello,

Yes this is for the subscription API. I am able to make a subscription with
a shorter URL but google webhooks does not allow to shorten the URL so I
hope you can change it to accept longer urls.

My code from on Google Scripts:

function createBolSubscription(){
  var url = 'https://api.bol.com/retailer/subscriptions';
  var payload = JSON.stringify({
      "resources": ['PROCESS_STATUS'],
      "url": "
https://script.google.com/macros/s/AKfycbwHH4O3Readjmpn-R56fwpLFdCTrHEKXEVVsTSSmSY3JlOuQFWLfJ1g/exec"
*//URL IS TOO LONG MAX. 90 CHAR*
    })
  var res = UrlFetchApp.fetch(url, {
    method: 'post',
    headers: {
      'Accept' : 'application/vnd.retailer.v4+json',
      'Content-Type' : 'application/vnd.retailer.v4+json',
      'Authorization': bolLogin(),
    },
    payload : payload,
    muteHttpExceptions: true
  });
  Logger.log(res);
}

Met vriendelijke groet, / Kind Regards,
Jan Portheine - CEO

[image: Handtekening Afbeelding] <http://shop.kartent.com>

*KarTent NL* (Waterproof?! <https://www.youtube.com/watch?v=4INmWMx5cSw>)
Keienbergweg 38A, 1101 GC
Amsterdam, The Netherlands
+31207865553
jan@kartent.com
www.kartent.com
[image: Facebook] <https://www.facebook.com/KarTentwebshop/> [image:
Twitter] <https://twitter.com/KarTent_> [image: LinkedIn]
<https://nl.linkedin.com/company/kartent> [image: YouTube]
<https://www.youtube.com/channel/UCIAg1HsGB0sSmsNXcx_Ytvg> [image:
Instagram] <https://www.instagram.com/kartent_webshop/> [image: Skype]


Op ma 18 jan. 2021 om 07:49 schreef mroosendaal <notifications@github.com>:

**Comment by mroosendaal** [comment]
@janportheine thanks for the input, we will have a look at it and will get back to you asap

**Comment by mroosendaal** [comment]
@janportheine it seems that we can add URLs with more characters than 90 so i'm not sure what's going on. When do you get the error that it's too long? When actually posting (if so could you provide a screenshot or the actual errormessage you get from us? Or is the script executed during your call and results in an error before the actual post?

**Comment by mroosendaal** [comment]
@janportheine it seems that we can add URLs with more characters than 90 so i'm not sure what's going on. When do you get the error that it's too long? When actually posting (if so could you provide a screenshot or the actual errormessage you get from us? Or is the script executed during your call and results in an error before the actual post?

**Comment by janportheine** [comment]
Hi M Roosendaal,

This is the notification I got back from the bol team:
*A problem occurred handling a request: /problems/validation-failed {400,
Your request parameters didn't validate., violations=[{name=url,
reason=size must be between 0 and 80}]}*

I could not find the error myself but if I create a subscription with a
long URL it does not work but a short one does:
function createBolSubscription(){
  var url = 'https://api.bol.com/retailer/subscriptions';
  var payload = JSON.stringify({
      "resources": ['PROCESS_STATUS'],
      "url": "
https://script.google.com/macros/s/AKfycbwHH4O3Readjmpn-R56fwpLFdCTrHEKXEVVsTSSmSY3JlOuQFWLfJ1g/exec"
//LONG URL DOES NOT WORK
    })
  var res = UrlFetchApp.fetch(url, {
    method: 'post',
    headers: {
      'Accept' : 'application/vnd.retailer.v4+json',
      'Content-Type' : 'application/vnd.retailer.v4+json',
      'Authorization': bolLogin(),
    },
    payload : payload,
    muteHttpExceptions: true
  });
}

ANy ideas?

Met vriendelijke groet, / Kind Regards,
Jan Portheine - CEO

[image: Handtekening Afbeelding] <http://shop.kartent.com>

*KarTent NL* (Waterproof?! <https://www.youtube.com/watch?v=4INmWMx5cSw>)
Keienbergweg 38A, 1101 GC
Amsterdam, The Netherlands
+31207865553
jan@kartent.com
www.kartent.com
[image: Facebook] <https://www.facebook.com/KarTentwebshop/> [image:
Twitter] <https://twitter.com/KarTent_> [image: LinkedIn]
<https://nl.linkedin.com/company/kartent> [image: YouTube]
<https://www.youtube.com/channel/UCIAg1HsGB0sSmsNXcx_Ytvg> [image:
Instagram] <https://www.instagram.com/kartent_webshop/> [image: Skype]


Op di 19 jan. 2021 om 14:54 schreef mroosendaal <notifications@github.com>:

**Comment by mroosendaal** [comment]
@janportheine you were correct, we did find a bug in de code which we will fix quickly and allow for up to 255 chars for a URL. I will let you know as soon as this is on production

**Comment by mroosendaal** [comment]
@janportheine we have fixed the issue, could you try again?

**Comment by janportheine** [comment]
Yes that worked! Test request has also been received. Thanks!

Met vriendelijke groet, / Kind Regards,
Jan Portheine - CEO

[image: Handtekening Afbeelding] <http://shop.kartent.com>

*KarTent NL* (Waterproof?! <https://www.youtube.com/watch?v=4INmWMx5cSw>)
Keienbergweg 38A, 1101 GC
Amsterdam, The Netherlands
+31207865553
jan@kartent.com
www.kartent.com
[image: Facebook] <https://www.facebook.com/KarTentwebshop/> [image:
Twitter] <https://twitter.com/KarTent_> [image: LinkedIn]
<https://nl.linkedin.com/company/kartent> [image: YouTube]
<https://www.youtube.com/channel/UCIAg1HsGB0sSmsNXcx_Ytvg> [image:
Instagram] <https://www.instagram.com/kartent_webshop/> [image: Skype]


Op vr 22 jan. 2021 om 11:19 schreef mroosendaal <notifications@github.com>:

**Comment by mroosendaal** [comment]
@janportheine great! If you have any questions related to our subscriptions let us know. We've just released a security feature to validate that message originated from bol.com: https://api.bol.com/retailer/public/Retailer-API/beta-program/subscription-api.html#_request_signing

**Comment by janportheine** [comment]
Will I now receive a push notification when a new order is placed?

Met vriendelijke groet, / Kind Regards,
Jan Portheine - CEO

[image: Handtekening Afbeelding] <http://shop.kartent.com>

*KarTent NL* (Waterproof?! <https://www.youtube.com/watch?v=4INmWMx5cSw>)
Keienbergweg 38A, 1101 GC
Amsterdam, The Netherlands
+31207865553
jan@kartent.com
www.kartent.com
[image: Facebook] <https://www.facebook.com/KarTentwebshop/> [image:
Twitter] <https://twitter.com/KarTent_> [image: LinkedIn]
<https://nl.linkedin.com/company/kartent> [image: YouTube]
<https://www.youtube.com/channel/UCIAg1HsGB0sSmsNXcx_Ytvg> [image:
Instagram] <https://www.instagram.com/kartent_webshop/> [image: Skype]


Op vr 22 jan. 2021 om 14:57 schreef mroosendaal <notifications@github.com>:

**Comment by mroosendaal** [comment]
Unfortunatly no, the [scope ](https://api.bol.com/retailer/public/Retailer-API/beta-program/subscription-api.html)is now "Currently our API only supports polling of our process status events, by sending requests to the Retailer API", so any action you initiated and normally need to check with polling the proces-status id, can now be done through push notifications. Later this year we hope to add events that were initiated from our side and/or customers.

**Comment by janportheine** [comment]
Ah okay, I hoped this would have been possible as it saves sending requests
to the server to check for orders.

Met vriendelijke groet, / Kind Regards,
Jan Portheine - CEO

[image: Handtekening Afbeelding] <http://shop.kartent.com>

*KarTent NL* (Waterproof?! <https://www.youtube.com/watch?v=4INmWMx5cSw>)
Keienbergweg 38A, 1101 GC
Amsterdam, The Netherlands
+31207865553
jan@kartent.com
www.kartent.com
[image: Facebook] <https://www.facebook.com/KarTentwebshop/> [image:
Twitter] <https://twitter.com/KarTent_> [image: LinkedIn]
<https://nl.linkedin.com/company/kartent> [image: YouTube]
<https://www.youtube.com/channel/UCIAg1HsGB0sSmsNXcx_Ytvg> [image:
Instagram] <https://www.instagram.com/kartent_webshop/> [image: Skype]


Op vr 22 jan. 2021 om 15:07 schreef mroosendaal <notifications@github.com>:
